name: infra

services:
  portainer:
    image: portainer/portainer-ce:2.27.0
    environment:
      - HOST
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${HOST}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

  traefik:
    image: traefik:v3.7.1
    container_name: traefik
    environment:
      - HOST
    command:
      - "--configFile=/traefik.toml"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_${HOST}.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${HOST}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$7i8yEufb$$LlISk/PPdwyHfBgUuHaST1"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.docker.network=proxy"
    restart: always

volumes:
  portainer_data:

networks:
  proxy:
    name: proxy
    external: false
