[api]
  dashboard = true

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers]
  [providers.docker]
    network = "proxy"
    watch = true
    exposedByDefault = false
