[api]
  dashboard = true

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
      permanent = true
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    network = "proxy"
    watch = true
    exposedByDefault = false

[certificatesResolvers]
  [certificatesResolvers.letsencrypt.acme]
    email = "michael.litschauer@gmail.com"
    storage = "acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
      entryPoint = "web"
