# copy scripts to digitalocean and run docker-compose

name: docker-compose

on: [push]

jobs:
  deploy_production:
    if: startsWith(github.ref, 'refs/tags/')
    name: production deployment to digitalocean.com
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: copy files
        uses: alinz/ssh-scp-action@master
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          host: ${{ secrets.APP_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_before: |
            echo 'PRODUCTION: deploying ${{ github.ref }}'
            mkdir -p /var/gendercomics/docker

          scp: |
            ./docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.APP_HOST }}:/var/gendercomics/docker/docker-compose.yml
            ./setup.sh ${{ secrets.DEPLOY_USER }}@${{ secrets.APP_HOST }}:/var/gendercomics/docker/setup.sh
            ./cleanup.sh ${{ secrets.DEPLOY_USER }}@${{ secrets.APP_HOST }}:/var/gendercomics/docker/cleanup.sh

          ssh_after: |
            chmod +x /var/gendercomics/docker/setup.sh /var/gendercomics/docker/cleanup.sh
            docker network create proxy    2>/dev/null || true
            docker network create database 2>/dev/null || true
            cd /var/gendercomics/docker
            docker compose up -d
            echo 'DONE!!!'
